FROM openjdk:13-alpine
RUN apk add --update \
    bash \
    ffmpeg \
  && rm -rf /var/cache/apk/*
WORKDIR /app
COPY anystream-server/build/install ./install
COPY anystream-client-web/build/distributions ./client-web
ENTRYPOINT ["./install/anystream-server-shadow/bin/anystream-server"]