FROM mcr.microsoft.com/java/jre:11-zulu-alpine

RUN apk add --update --no-cache bash ffmpeg

WORKDIR /app

COPY anystream-server/server-app/build/install ./install/
COPY anystream-client-web/build/dist/js/productionExecutable ./client-web/

ENV DATA_PATH=/app/storage/
ENV DATABASE_URL=sqlite:/app/storage/config/anystream.db
ENV FFMPEG_PATH=/usr/bin
ENV WEB_CLIENT_PATH=/app/client-web
ENV PORT=8888

ENTRYPOINT ["./install/anystream-server/bin/anystream"]
