site_name: AnyStream
site_description: A self-hosted streaming service for your media collection.
site_url: https://docs.anystream.dev/
repo_url: https://github.com/drewcarlson/anystream
remote_branch: gh-pages
docs_dir: docs
copyright: 'Copyright &copy; 2023 AnyStream Maintainers'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/as-emblem.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mike
  - markdownextradata: {}

extra:
  as_version: !ENV [VERSION, '0.0.1-test']
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/heart
      link: https://github.com/sponsors/DrewCarlson
    - icon: fontawesome/brands/github
      link: https://github.com/DrewCarlson/AnyStream
    - icon: fontawesome/brands/docker
      link: https://github.com/DrewCarlson/AnyStream/pkgs/container/anystream

nav:
  - Home: index.md
  - Getting Started: 1-getting-started.md
  - Library Management: 2-library-management.md
  - Clients and Mobile Apps: 3-clients-and-mobile.md
  - Connecting qBittorrent: 4-connecting-qbittorrent.md
  - Development:
    - Documentation: development/documentation.md