[versions]
kotlin = "1.6.10"
coroutines = "1.5.2-native-mt"
serialization = "1.3.1"
ktorio = "1.6.7"
composejb = "1.0.1-rc2"
kotlinjs_ext = "1.0.1-pre.276-kotlin-1.6.0"

qbittorrent = "0.3.0"
torrent_search = "0.1.1"
mobiuskt = "0.3.1"
ktor_perm = "0.1.4"

korlibs_korio = "2.2.1"
kmongo = "4.4.0"
bouncy_castle = "1.67"
tmdb = "1.12"
jaffree = "2021.11.06"
logback = "1.2.1"
shadowjar = "7.1.0"

zxing = "3.3.0"
anr_watchdog = "1.4.0"
compose = "1.1.0-rc01"
composeCompiler = "1.1.0-rc02"
exoplayer = "2.16.1"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composejb = { id = "org.jetbrains.compose", version.ref = "composejb" }
androidkt = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowjar" }

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

kotlinjs-extensions = { module = "org.jetbrains.kotlin-wrappers:kotlin-extensions", version.ref = "kotlinjs_ext" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorio" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorio" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorio" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorio" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktorio" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktorio" }

ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorio" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorio" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktorio" }
ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktorio" }
ktor-server-metrics = { module = "io.ktor:ktor-metrics", version.ref = "ktorio" }
ktor-server-auth = { module = "io.ktor:ktor-auth", version.ref = "ktorio" }
ktor-server-authJwt = { module = "io.ktor:ktor-auth-jwt", version.ref = "ktorio" }
ktor-server-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktorio" }
ktor-server-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktorio" }
ktor-server-permissions = { module = "org.drewcarlson:ktor-permissions", version.ref = "ktor_perm" }

korio = { module = "com.soywiz.korlibs.korio:korio", version.ref = "korlibs_korio" }

qbittorrent-models = { module = "org.drewcarlson:qbittorrent-models", version.ref = "qbittorrent" }
qbittorrent-client = { module = "org.drewcarlson:qbittorrent-client", version.ref = "qbittorrent" }

anrWatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anr_watchdog" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exoplayer-hls = { module = "com.google.android.exoplayer:exoplayer-hls", version.ref = "exoplayer" }

torrentSearch = { module = "org.drewcarlson:torrentsearch", version.ref = "torrent_search" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }

jaffree = { module = "com.github.kokorin.jaffree:jaffree", version.ref = "jaffree" }

bouncyCastle = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncy_castle" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

tmdbapi = { module = "com.github.holgerbrandl:themoviedbapi", version.ref = "tmdb" }

kmongo-coroutine-serialization = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0" }
androidx-appcompat-core = { module = "androidx.appcompat:appcompat", version = "1.4.0" }
androidx-leanback-core = { module = "androidx.leanback:leanback", version = "1.1.0-rc02" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.4.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }

coil = { module = "io.coil-kt:coil-compose", version = "1.4.0" }
routingCompose = { module = "app.softwork:routing-compose", version = "0.1.4" }

quickie-bundled = { module = "io.github.g00fy2.quickie:quickie-bundled", version = "1.2.3" }

mobiuskt-core = { module = "org.drewcarlson:mobiuskt-core", version.ref = "mobiuskt" }
mobiuskt-extras = { module = "org.drewcarlson:mobiuskt-extras", version.ref = "mobiuskt" }
mobiuskt-android = { module = "org.drewcarlson:mobiuskt-android", version.ref = "mobiuskt" }
mobiuskt-coroutines = { module = "org.drewcarlson:mobiuskt-coroutines", version.ref = "mobiuskt" }

[bundles]
exoplayer = [ "exoplayer-core", "exoplayer-ui", "exoplayer-hls" ]
compose = [ "compose-ui-ui", "compose-ui-tooling", "compose-foundation", "compose-material" ]
