INSERT INTO streamEncoding(id,
                           codecName,
                           rawProbeData,
                           'index',
                           language,
                           profile,
                           bitRate,
                           channels,
                           level,
                           height,
                           width,
                           type)
VALUES (NULL,
        :stream.codecName,
        :stream.rawProbeData,
        :stream.index,
        :stream.language,
        :stream.profile,
        :stream.bitRate,
        :stream.channels,
        :stream.level,
        :stream.height,
        :stream.width,
        :stream.type)