name: Spotless

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.android.outputs.any_changed }}
      client-core: ${{ steps.client-core.outputs.any_changed }}
      client-api: ${{ steps.client-api.outputs.any_changed }}
      data-models: ${{ steps.data-models.outputs.any_changed }}
      ios: ${{ steps.ios.outputs.any_changed }}
      web: ${{ steps.web.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: android
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/anystream-client-android/**/*.kt
            **/anystream-client-android/**/*.kts
      - name: Get changed files
        id: client-core
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/anystream-client-core/**/*.kt
            **/anystream-client-core/**/*.kts
      - name: Get changed files
        id: data-models
        uses: tj-actions/changed-files@v19
        with:
          files: |
            gradle/libs.versions.toml
            **/anystream-data-models/**/*.kt
            **/anystream-data-models/**/*.kts
      - name: Get changed files
        id: server
        uses: tj-actions/changed-files@v19
        with:
          files: |
            gradle/libs.versions.toml
            **/anystream-server/**/*.kt
            **/anystream-server/**/*.kts
      - name: Get changed files
        id: ios
        uses: tj-actions/changed-files@v19
        with:
          files: |
            gradle/libs.versions.toml
            **/anystream-client-ios/**/*.kt
            **/anystream-client-ios/**/*.kts
      - name: Get changed files
        id: web
        uses: tj-actions/changed-files@v19
        with:
          files: |
            gradle/libs.versions.toml
            **/anystream-client-web/**/*.kt
            **/anystream-client-web/**/*.kts

  client-android:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.android == 'true' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Spotless Check
        with:
          arguments: anystream-client-android:spotlessCheck

  client-core:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.client-core == 'true' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Spotless Check
        with:
          arguments: anystream-client-core:spotlessCheck

  client-web:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.web == 'true' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Spotless Check
        with:
          arguments: anystream-client-web:spotlessCheck

  data-models:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.data-models == 'true' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Spotless Check
        with:
          arguments: anystream-data-models:spotlessCheck

  server:
    runs-on: ubuntu-latest
    needs: [ file-changes ]
    if: needs.file-changes.outputs.server == 'true' || github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/gradle-build-action@v2
        name: Spotless Check
        with:
          arguments: anystream-server:spotlessCheck
