name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DATABASE_URL: ":memory:"

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.android.outputs.any_changed }}
      client-core: ${{ steps.client-core.outputs.any_changed }}
      client-ui: ${{ steps.client-ui.outputs.any_changed }}
      data-models: ${{ steps.data-models.outputs.any_changed }}
      ios: ${{ steps.ios.outputs.any_changed }}
      web: ${{ steps.web.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Get changed files
        id: android
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            build.gradle.kts
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            gradle/libsAndroid.versions.toml
            **/client/android/**
            **/client/core/src/commonMain/**
            **/client/core/src/commonTest/**
            **/client/core/src/androidMain/**
            **/client/data-models/**
      - name: Get changed files
        id: client-core
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            **/client/core/**
            **/client/data-models/**
      - name: Get changed files
        id: client-ui
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            gradle/libsAndroid.versions.toml
            **/client/ui/**
            **/client/core/**
            **/client/presentation/**
            **/client/data-models/**
      - name: Get changed files
        id: data-models
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            **/client/data-models/**
      - name: Get changed files
        id: server
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsServer.versions.toml
            **/client/data-models/**
            **/server/**
      - name: Get changed files
        id: ios
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            **/client/ios/**
            **/client/core/src/commonMain/**
            **/client/core/src/commonTest/**
            **/client/core/src/iosMain/**
            **/client/data-models/**
      - name: Get changed files
        id: web
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            gradle/kotlin-js-store/**
            **/client/web/**
            **/client/core/src/commonMain/**
            **/client/presentation/src/commonMain/**
            **/client/data-models/**
      - name: Get changed files
        id: desktop
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            gradle/libsCommon.versions.toml
            gradle/libsClient.versions.toml
            gradle/kotlin-js-store/**
            **/client/desktop/**
            **/client/core/src/commonMain/**
            **/client/presentation/src/commonMain/**
            **/client/data-models/**

  client-core-tests:
    needs: [ file-changes ]
    if: needs.file-changes.outputs.client-core == 'true' || github.ref_name == 'main'
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] #windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v3

      - uses: browser-actions/setup-firefox@fcf821c621167805dd63a29662bd7cb5676c81a8 # v1.7.1
        id: install-firefox

      - name: Set FIREFOX_BIN environment variable
        run: echo "FIREFOX_BIN=${{ steps.install-firefox.outputs.firefox-path }}" >> $GITHUB_ENV

      - name: All Tests
        run: ./gradlew client:core:allTests #client:core:koverXmlReport

      - name: Archive Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: reports-client-core-${{ matrix.os }}
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # v6.3.1
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'

  client-ui-tests:
    needs: [ file-changes ]
    if: needs.file-changes.outputs.client-ui == 'true' || github.ref_name == 'main'
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] #windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v3

      - name: All Tests
        run: ./gradlew client:ui:allTests #client:ui:koverXmlReport

      - name: Archive Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: reports-client-ui-${{ matrix.os }}
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # v6.3.1
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'

  client-android-tests:
    needs: [ file-changes ]
    if: needs.file-changes.outputs.android == 'true' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: DrewCarlson/android-emulator-runner@400f29c9684faec377be4e12c97daddf5c779c75
        name: Test Android Targets
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_7_pro
          script: ./gradlew androidConnectedCheck connectedCheck

      - name: Archive Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: reports-client-android
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # v6.3.1
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'

  client-web-tests:
    needs: [ file-changes ]
    if: needs.file-changes.outputs.web == 'true' || github.ref_name == 'main'
    strategy:
      matrix:
        os: [ ubuntu-latest ] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v3

      - uses: browser-actions/setup-firefox@fcf821c621167805dd63a29662bd7cb5676c81a8 # v1.7.1
        id: install-firefox

      - name: Set FIREFOX_BIN environment variable
        run: echo "FIREFOX_BIN=${{ steps.install-firefox.outputs.firefox-path }}" >> $GITHUB_ENV

      - name: Web Tests
        run: ./gradlew client:web:jsBrowserTest #client:web:koverXmlReport

      - name: Archive Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: reports-client-web-${{ matrix.os }}
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # v6.3.1
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'

  client-desktop-tests:
    needs: [ file-changes ]
    if: needs.file-changes.outputs.desktop == 'true' || github.ref_name == 'main'
    strategy:
      matrix:
        os: [ ubuntu-latest ] # macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v3

      - name: Desktop Tests
        run: ./gradlew client:desktop:build #client:desktop:koverXmlReport

  server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v3

      - name: Run Server Tests
        run: >
          ./gradlew
          server:application:test
          server:db-models:test
          server:library-manager:test
          server:metadata-manager:test
          server:shared:test
          server:stream-service:test

      - name: Archive Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: reports-server
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@49b2ca06f62aa7ef83ae6769a2179271e160d8e4 # v6.3.1
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'

  upload-kover-reports:
    runs-on: ubuntu-latest
    needs: [ server-tests, client-core-tests, client-web-tests ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download kover reports
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: reports*
      - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/build/reports/kover/project-xml/report.xml"
