name: Yarn Lock Sync

on:
  push:
    branches:
      - 'renovate/**'

concurrency:
  group: yarn-upgrade-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  yarn-lock-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Cache Build files
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - name: Yarn Lock Upgrade
        run: ./gradlew kotlinUpgradeYarnLock

      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          author_name: renovate[bot]
          author_email: 29139614+renovate[bot]@users.noreply.github.com
          message: Upgrade yarn.lock file
